Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2022-08, with the labels that each got.

#27 German Translation
  index.de-DE.md
  install-guides/windows/gog-install-german.md
  install-guides/windows/humble-install-german.md
  install-guides/windows/index-german.md
  install-guides/windows/other-sources-german.md
  install-guides/windows/steam-install-german.md
  install-guides/windows/windows-slipstream-german.md
Labels: documentation, enhancement

#28 Update index.md
  _i18n/de/index.md
Labels: documentation

#35 Some German image translations
  Mod Files/Hyperspace.ftl
  Mod Files/img/loc-de/customizeUI/unlocks_disabled-old.png
  Mod Files/img/loc-de/customizeUI/unlocks_disabled.png
Labels: enhancement, translation
