Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2024-02, with the labels that each got.

#220 Exposing EffectsBlueprint & Adding %template for vector<StatBoostDefinition*>
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#219 Add a ShipObject section to the wiki
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#218 pages updates
  Gemfile.lock
  _i18n/de/index.md
  _i18n/de/install-guides/mac/index.md
  _i18n/de/install-guides/windows/windows-slipstream.md
  _i18n/en/index.md
  _i18n/en/install-guides/mac/index.md
  _i18n/en/install-guides/windows/windows-slipstream.md
  _i18n/ko/index.md
  _i18n/ko/install-guides/mac/index.md
  _i18n/ko/install-guides/windows/windows-slipstream.md
  install-guides/mac/index.md
Labels: documentation

#161 Fixed ion bug (Issue #132)
  CustomDrones.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  HSVersion.h
  Misc.cpp
  Mod Files/data/hyperspace.xml
  Mod Files/data/text-de.xml.append
  Mod Files/data/text_misc.xml.append
  Mod Files/img/icons/locking/s_octa_9+_base.png
  Mod Files/img/icons/locking/s_ring_9+_base.png
  Mod Files/mod-appendix/metadata.xml
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipSystem.zhl
Labels: bug, zhl

#179 Implemented ON_WAIT callback
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
  lua/InternalEvents.cpp
  lua/InternalEvents.h
  wiki/Lua-Defines-module.md
Labels: enhancement, zhl

#235 Remake of the Hyperspace build instructions for Windows
  BUILDING.WINDOWS.md
  wiki/Lua-Hyperspace-Module.md
  wiki/img/building-tutorial/badwsl.png
  wiki/img/building-tutorial/board.png
  wiki/img/building-tutorial/clonehs.png
  wiki/img/building-tutorial/goodwsl.png
  wiki/img/building-tutorial/hyper-v.png
  wiki/img/building-tutorial/hypererror.png
  wiki/img/building-tutorial/reachsh.png
  wiki/img/building-tutorial/winfeat.png
  wiki/img/building-tutorial/wslUbuntu.png
  wiki/img/building-tutorial/wsldocker.png
Labels: documentation

#160 SpaceStatus stuff (Issue #84)
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Misc.cpp
  Mod Files/data/text-de.xml.append
  Mod Files/data/text_misc.xml.append
  Mod Files/data/text_tooltips.xml.append
  Mod Files/img/warnings/backglow_warning_yellow.png
  Mod Files/img/warnings/danger_pds_neutral.png
  libzhlgen/test/functions/ELF_amd64/1.6.13/MouseControl.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/SpaceStatus.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/MouseControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SpaceStatus.zhl
  libzhlgen/test/functions/win32/1.6.9/MouseControl.zhl
  libzhlgen/test/functions/win32/1.6.9/SpaceStatus.zhl
  lua/RenderEvents.h
  wiki/Lua-Defines-module.md
Labels: bug, enhancement, zhl

#48 Custom localization
  CMakeLists.txt
  CustomLocalization.cpp
  CustomLocalization.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/LanguageChooser.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ResourceControl.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/TextLibrary.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/freetype.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/LanguageChooser.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ResourceControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/TextLibrary.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/freetype.zhl
  libzhlgen/test/functions/win32/1.6.9/LanguageChooser.zhl
  libzhlgen/test/functions/win32/1.6.9/ResourceControl.zhl
  libzhlgen/test/functions/win32/1.6.9/TextLibrary.zhl
  libzhlgen/test/functions/win32/1.6.9/freetype.zhl
Labels: enhancement, translation, zhl

#185 Custom mind control
  CustomSystems.cpp
  CustomSystems.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  libzhlgen/test/functions/ELF_amd64/1.6.13/MindSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/MindSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/MindSystem.zhl
Labels: bug, enhancement, zhl

#225 Locked Miniship Icon prioritize _base.png version
  CustomShipSelect.cpp
Labels: enhancement

#242 Locked Miniship Icon prioritize _base.png version (fix)
  CustomShipSelect.cpp
Labels: enhancement

#245 add callback to set seed
  Seeds.cpp
  lua/InternalEvents.h
  wiki/Lua-Defines-module.md
Labels: enhancement
