Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2024-04, with the labels that each got.

#264 Exposed Sector Name & Current Score
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#250 Fix miscolored pixels on small autofire toggle button.
  Mod Files/img/button_small_autofireOff_off.png
  Mod Files/img/button_small_autofireOff_on.png
  Mod Files/img/button_small_autofireOff_select2.png
  Mod Files/img/button_small_autofireOn_off.png
  Mod Files/img/button_small_autofireOn_on.png
  Mod Files/img/button_small_autofireOn_select2.png
Labels: bug

#241 Added "SYS ALL" console command
  .gitignore
  CommandConsole.cpp
  Mod Files/data/hyperspace.xml
Labels: enhancement

#272 add community korean translation
  Mod Files/data/hyperspace.xml
  Mod Files/data/names.xml.append
  Mod Files/data/text-ko.xml
  Mod Files/fonts/ko/gmarketsans.ttf
Labels: enhancement

#238 Refactoring tooltips
  Mod Files/data/text_misc.xml.append
  RedesignedTooltips.cpp
Labels: enhancement

#271 Exposed Slot
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/CrewMember.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CrewMember.zhl
  libzhlgen/test/functions/win32/1.6.9/CrewMember.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#269 Exposed Ship:GetHullBreaches
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#270 Exposed AddCrewMember functions for ShipManager
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#251 Add a "force" attribute that allows recallBoarders to recall crew who can't teleport
  CustomEvents.cpp
  CustomEvents.h
  Mod Files/data/hyperspace.xml
Labels: enhancement

#263 Expose ShipInfo::augList
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#254 Expose CombatControl.position and WeaponControl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#274 Linked an updated video for macOS
  _i18n/de/install-guides/mac/index.md
  _i18n/en/install-guides/mac/index.md
  _i18n/ko/install-guides/mac/index.md
Labels: documentation

#261 Expose Equipment
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/Equipment.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Equipment.zhl
  libzhlgen/test/functions/win32/1.6.9/Equipment.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#280 add shortcut to access the CApp instance in lua
  Misc.cpp
  Misc.h
  lua/modules/hyperspace.i
Labels: enhancement

#281 Display additional ship info in the hangar
  CustomOptions.h
  CustomShipSelect.cpp
  Mod Files/data/hyperspace.xml
  Mod Files/img/customizeUI/shipresources_crewlimit_box.png
  Mod Files/img/customizeUI/shipresources_drones_box.png
  Mod Files/img/customizeUI/shipresources_missiles_box.png
  Resources.cpp
Labels: enhancement

#257 CreditScreen - Reimplementation
  CommandConsole.cpp
  CustomEvents.cpp
  CustomEvents.h
  CustomOptions.h
  CustomShipSelect.cpp
  Mod Files/data/hyperspace.xml
  Mod Files/data/text_misc.xml.append
  Mod Files/data/text_tooltips.xml.append
  Resources.cpp
  buildscripts/windows/build-debugonly-from-docker.sh
  buildscripts/windows/build-debugonly.sh
  buildscripts/windows/build-releaseonly-from-docker.sh
  buildscripts/windows/build-releaseonly.sh
Labels: enhancement
