Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2024-07, with the labels that each got.

#294 fix weapons with iconReplace rendering resource box at wrong size
  CustomWeapons.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponBlueprint.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponBlueprint.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponBlueprint.zhl
Labels: bug, zhl

#286 Changed seed display and resource count font to a numeric font (fixes seed text missing in hangar with non-Latin)
  CustomShipSelect.cpp
Labels: bug

#275 Fixed misspelling of %nodefaultctors/%nodefaultdtors SWIG directive
  lua/modules/hyperspace.i
Labels: bug

#287 fixing ACH command and adding ACH_LOCK command
  CommandConsole.cpp
  CustomAchievements.cpp
  CustomAchievements.h
  Mod Files/data/hyperspace.xml
  lua/modules/hyperspace.i
Labels: hs bug, enhancement

#301 add SET_BONUS_POWER callback
  Misc.cpp
  lua/InternalEvents.h
  lua/LuaLibScript.h
  lua/modules/hyperspace.i
  wiki/Lua-Defines-module.md
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement
