Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2024-12, with the labels that each got.

#402 fix move command on partitioned ships
  CustomCrew.cpp
Labels: vanilla bug

#397 Fix save file breaks when saving whilst a weapon still has queued projectiles
  CustomDamage.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/ProjectileFactory.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponAnimation.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ProjectileFactory.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponAnimation.zhl
  libzhlgen/test/functions/win32/1.6.9/ProjectileFactory.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponAnimation.zhl
Labels: hs bug, zhl

#407 exposing GL_DrawCircle
  lua/modules/graphics.i
  wiki/Lua-Graphics-Module.md
Labels: enhancement

#405 expose custom ship unlock
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#394 Add overloads for hs_log_file
  Global.cpp
  Global.h
Labels: enhancement

#386 Exposed LockdownShard
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/Ship.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Ship.zhl
  libzhlgen/test/functions/win32/1.6.9/Ship.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#400 Adding LocationEvent::AddChoice & LocationEvent::RemoveEvent
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/EventGenerator.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/LocationEvent.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/EventGenerator.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/LocationEvent.zhl
  libzhlgen/test/functions/win32/1.6.9/EventGenerator.zhl
  libzhlgen/test/functions/win32/1.6.9/LocationEvent.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement

#410 Exposing BreachSpecificHull
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/Ship.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Ship.zhl
  libzhlgen/test/functions/win32/1.6.9/Ship.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement

#369 Various improvement for system upgrade UI visualization
  CustomUpgrades.cpp
  CustomUpgrades.h
  Mod Files/data/hyperspace.xml
  Mod Files/data/text-de.xml.append
  Mod Files/data/text-es.xml.append
  Mod Files/data/text-fr.xml.append
  Mod Files/data/text-it.xml.append
  Mod Files/data/text-ja.xml.append
  Mod Files/data/text-ko.xml.append
  Mod Files/data/text-pl.xml.append
  Mod Files/data/text-pt.xml.append
  Mod Files/data/text-ru.xml.append
  Mod Files/data/text-zh-Hans.xml.append
  Mod Files/data/text_misc.xml.append
  Resources.cpp
Labels: enhancement

#409 Expose Weapon Control related fields
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement
