Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2024-09, with the labels that each got.

#329 fixing the beacon cursor still being available when out of fuel
  CustomMap.cpp
Labels: hs bug

#332 fix buggy return to stations on partitioned ships
  CustomCrew.cpp
  CustomShipSelect.cpp
  CustomShipSelect.h
  Mod Files/data/hyperspace.xml
Labels: vanilla bug

#330 Fixing free hull repair exploit with the repair drone and the recovery arm
  Balance.cpp
  Balance.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/DroneSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/DroneSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/DroneSystem.zhl
Labels: zhl, vanilla bug

#334 fix for arty vanishing from gibs
  CustomShipSelect.cpp
  CustomShipSelect.h
  CustomShips.cpp
  CustomShips.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/ExplosionAnimation.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponAnimation.zhl
  libzhlgen/test/functions/ELF_amd64/FTLGameStripped.h
  libzhlgen/test/functions/ELF_x86/1.6.13/ExplosionAnimation.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponAnimation.zhl
  libzhlgen/test/functions/ELF_x86/FTLGameStripped.ELF32.h
  libzhlgen/test/functions/win32/1.6.9/ExplosionAnimation.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponAnimation.zhl
  libzhlgen/test/functions/win32/FTLGameStripped.h
Labels: zhl, vanilla bug

#336 fixing RoomAnim::SaveState & RoomAnim::LoadState method
  CustomShips.cpp
Labels: hs bug

#333 fixes for overflowing enemy HP bar
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  HullNumbers.cpp
  HullNumbers.h
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/CachedImage.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CachedImage.zhl
  libzhlgen/test/functions/win32/1.6.9/CachedImage.zhl
Labels: enhancement, zhl

#328 Lua_Hyperspace_Module.md wiki update
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#319 Exposed SCrewStats and added docs for CrewMember.
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#331 [Wiki Update] add TextString description and item "Value" to SDL key table
  wiki/Lua-Defines-module.md
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#348 fix layering for artillery on gibs
  CustomShips.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/ExplosionAnimation.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ExplosionAnimation.zhl
  libzhlgen/test/functions/win32/1.6.9/ExplosionAnimation.zhl
Labels: hs bug, zhl

#343 Fixing shipgraph wiki entry for two of its method
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#358 [Translation] Overwrite nameless-one with appropriate text as ship name in ja
  Mod Files/data/text-ja.xml.append
Labels: translation
