Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2024-10, with the labels that each got.

#360 Expanded ZHL documentation
  wiki/Finding-Signatures-with-Ghidra.md
  wiki/img/sig-tutorial/No-Unique-Match.png
  wiki/img/sig-tutorial/Non-RET-function-example.png
  wiki/img/sig-tutorial/Non-unique-function-example.png
  wiki/img/sig-tutorial/noHook-function-example.png
Labels: documentation

#371 add hideHullDuringExplosion
  CustomShipSelect.cpp
  CustomShipSelect.h
  CustomShips.cpp
  CustomShips.h
  Mod Files/data/hyperspace.xml
  Resources.cpp
Labels: enhancement

#367 add select armament event
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Misc.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponControl.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponControl.zhl
  lua/InternalEvents.h
  wiki/Lua-Defines-module.md
Labels: enhancement, zhl

#370 add crew hp render event
  Misc.cpp
  lua/RenderEvents.h
  wiki/Lua-Defines-module.md
Labels: enhancement

#353 Re-display seed initial text
  Seeds.cpp
Labels: hs bug

#366 add render event for ftl button layer
  Misc.cpp
  lua/RenderEvents.h
  lua/modules/hyperspace.i
  wiki/Lua-Defines-module.md
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#384 Exposed bPaused to Lua scripting, updated documentation
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#357 Allow rename input Japanese letters (fix issue 317)
  CustomOptions.h
  Misc.cpp
  Mod Files/data/hyperspace.xml
  Resources.cpp
Labels: enhancement

#380 Custom sound for achievements
  CustomAchievements.cpp
  CustomAchievements.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  libzhlgen/test/functions/ELF_amd64/1.6.13/AchievementTracker.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/AchievementTracker.zhl
  libzhlgen/test/functions/win32/1.6.9/AchievementTracker.zhl
Labels: enhancement, zhl

#375 FTL_JUMPER now taken into consideration in FTL_JUMPER_GOOD fuel cost
  Augments.cpp
Labels: hs bug

#373 Expose Combat Control Fields
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#351 Purchase limit indicator improvement
  CustomStore.cpp
  Mod Files/data/hyperspace.xml
  Mod Files/data/text-de.xml.append
  Mod Files/data/text-es.xml.append
  Mod Files/data/text-fr.xml.append
  Mod Files/data/text-it.xml.append
  Mod Files/data/text-ja.xml.append
  Mod Files/data/text-ko.xml.append
  Mod Files/data/text-pl.xml.append
  Mod Files/data/text-pt.xml.append
  Mod Files/data/text-ru.xml.append
  Mod Files/data/text-zh-Hans.xml.append
  Mod Files/data/text_tooltips.xml.append
  Mod Files/img/storeUI/store_limit_indicator.png
  Resources.cpp
  Store_Extend.h
Labels: enhancement

#361 Custom choice text color
  CustomColors.cpp
  CustomColors.h
  CustomOptions.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/EventsParser.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/EventsParser.zhl
  libzhlgen/test/functions/win32/1.6.9/EventsParser.zhl
Labels: enhancement, zhl

#376 Fixing badly exposed enums
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: hs bug
