Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2024-08, with the labels that each got.

#305 expose SetHackingLevel for all systems
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/MindSystem.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/Shields.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/MindSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Shields.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/MindSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/Shields.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/TeleportSystem.zhl
  lua/modules/hyperspace.i
Labels: enhancement, zhl

#302 Fix issue 296
  RedesignedTooltips.cpp
Labels: hs bug

#303 Fix issue 299
  CustomSystems.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/PowerManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/PowerManager.zhl
  libzhlgen/test/functions/win32/1.6.9/PowerManager.zhl
Labels: hs bug, zhl

#306 Expose hazard
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement

#289 Navigation bar for the command console input
  CommandConsole.cpp
  CommandConsole.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/InputBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/InputBox.zhl
  libzhlgen/test/functions/win32/1.6.9/InputBox.zhl
Labels: enhancement, zhl

#284 Exposed LocationEvent::loc; SectorDescription::type; the ChoiceReq; group and LocationEvent::Choice::requirement;
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#290 Added hullDamageResistChance which acts like sysDamageResistChance but for hull damage
  CustomShipSelect.cpp
  CustomShipSelect.h
  CustomShips.cpp
  Mod Files/data/hyperspace.xml
  Room_Extend.h
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#298 On run ship renaming feature in the upgrade menu
  CustomUpgrades.cpp
  CustomUpgrades.h
  Mod Files/data/hyperspace.xml
  Mod Files/img/upgradeUI/buttons_system_rename_on.png
  Mod Files/img/upgradeUI/buttons_system_rename_select2.png
  Resources.cpp
Labels: enhancement

#297 fixing CHOICEBOX callback not being called reliably, adding :GetChoices() for LocationEvent/ChoiceBox and modifying parsefuncs.lua
  CustomAugments.cpp
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  libzhlgen/lua/parsefuncs.lua
  libzhlgen/test/functions/ELF_amd64/1.6.13/ChoiceBox.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/LocationEvent.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ChoiceBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/LocationEvent.zhl
  libzhlgen/test/functions/win32/1.6.9/ChoiceBox.zhl
  libzhlgen/test/functions/win32/1.6.9/LocationEvent.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#309 Fix crash upgrades
  CustomUpgrades.cpp
Labels: hs bug

#293 Exposing Location (9 new fields) and new StarMap::MouseMove hook
  CustomMap.cpp
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#291 QoL: Fixing Random & Arrow button not moving to the corresponding ship page
  CustomShipSelect.cpp
  CustomShipSelect.h
Labels: enhancement

#310 Console cursor up
  CommandConsole.cpp
Labels: hs bug

#315 fix non-latin character input for command console
  CommandConsole.cpp
  CommandConsole.h
  Mod Files/data/hyperspace.xml
Labels: hs bug
