Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2025-03, with the labels that each got.

#524 Ability tooltip bugfix
  CustomCrew.cpp
Labels: hs bug

#520 Fixed player hull bar color being hardcoded to the 30HP range
  CustomSuperShield.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  HullNumbers.cpp
  HullNumbers.h
  Mod Files/data/hyperspace.xml
  Resources.cpp
  buildscripts/linux-1.6.13/build-releaseonly-from-docker.sh
  buildscripts/linux-1.6.13/build-releaseonly.sh
  libzhlgen/test/functions/ELF_amd64/1.6.13/CSurface.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipStatus.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CSurface.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipStatus.zhl
  libzhlgen/test/functions/win32/1.6.9/CSurface.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipStatus.zhl
Labels: zhl, vanilla bug

#519 Added the FLEET command which can be used to delay or advance the rebel fleet.
  CommandConsole.cpp
  Mod Files/data/hyperspace.xml
Labels: enhancement

#480 Add artillery hotkeys
  ArtillerySystem.cpp
  CustomHotkeys.cpp
  CustomSystems.cpp
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  Mod Files/data/text_misc.xml.append
  libzhlgen/test/functions/ELF_amd64/1.6.13/CombatControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CombatControl.zhl
  libzhlgen/test/functions/win32/1.6.9/CombatControl.zhl
Labels: enhancement, translation

#513 add removeNebula tag for quests
  CustomEvents.cpp
  CustomEvents.h
  Mod Files/data/hyperspace.xml
Labels: enhancement

#510 expose AugmentDefinition
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#516 ASB fixes
  CustomEvents.cpp
  Mod Files/data/hyperspace.xml
Labels: hs bug, documentation

#523 Fixed some edge cases with shotLimit
  CustomWeapons.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/Animation.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponAnimation.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Animation.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponAnimation.zhl
  libzhlgen/test/functions/win32/1.6.9/Animation.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponAnimation.zhl
Labels: hs bug, zhl

#529 Clone pages and reordering
  ArtillerySystem.cpp
  CMakeLists.txt
  CloneQueue.cpp
  CustomCommandGui.cpp
  CustomOptions.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  Input.cpp
  Mod Files/data/hyperspace.xml
  Resources.cpp
  SystemBox_Extend.cpp
  SystemBox_Extend.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/CloneBox.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/SystemBox.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/SystemControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CloneBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SystemBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SystemControl.zhl
  libzhlgen/test/functions/win32/1.6.9/CloneBox.zhl
  libzhlgen/test/functions/win32/1.6.9/SystemBox.zhl
  libzhlgen/test/functions/win32/1.6.9/SystemControl.zhl
Labels: enhancement, zhl

#514 Improve CustomEquipment
  CustomEquipment.cpp
  CustomEquipment.h
  CustomShipSelect.cpp
  Equipment_Extend.h
  Input.cpp
  Mod Files/data/hyperspace.xml
  Resources.cpp
Labels: enhancement

#527 Prevent the scrolling tooltip from overlapping the point of the cursor
  RedesignedTooltips.cpp
Labels: hs bug

#525 Disable low o2 warning sound with no o2 ships
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Misc.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipStatus.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipStatus.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipStatus.zhl
Labels: hs bug

#518 Improve artillery info UI
  CustomStore.cpp
  CustomUpgrades.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/SystemStoreBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SystemStoreBox.zhl
  libzhlgen/test/functions/win32/1.6.9/SystemStoreBox.zhl
Labels: enhancement, zhl

#543 fix game crashing on pulsar pulse for ships with no systems
  CustomShips.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
Labels: zhl, vanilla bug

#546 defenseDroneFix fix
  CustomDrones.cpp
  CustomDrones.h
  Resources.cpp
Labels: hs bug

#547 expose CustomAugmentManager::GetShipAugments
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement

#564 Prevent GetAugmentDefinition from causing crash when called from lua with invalid augment name
  lua/modules/hyperspace.i
Labels: hs bug

#565 Fix a bug with zoltan bypass
  CustomWeapons.cpp
Labels: hs bug

#517 Extend CustomTextStyle to other freetype functions
  CustomTextStyle.cpp
  CustomTextStyle.h
  wiki/Lua-Graphics-Module.md
Labels: enhancement

#495 add priorityEventsOverrideNebula for sector generation
  CustomEvents.cpp
  CustomEvents.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  libzhlgen/test/functions/win32/1.6.9/StatusEffect.zhl
Labels: enhancement

#487 System Exclusivity
  CommandConsole.cpp
  CustomEvents.cpp
  CustomEvents.h
  CustomOptions.h
  CustomShipSelect.cpp
  CustomShipSelect.h
  CustomStore.cpp
  CustomSystems.cpp
  CustomSystems.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  Mod Files/data/text_misc.xml.append
  Resources.cpp
  Systems.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/DroneSystem.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/FTLButton.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipObject.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/SystemStoreBox.zhl
  libzhlgen/test/functions/ELF_amd64/FTLGameStripped.h
  libzhlgen/test/functions/ELF_x86/1.6.13/DroneSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/FTLButton.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipObject.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SystemStoreBox.zhl
  libzhlgen/test/functions/ELF_x86/FTLGameStripped.ELF32.h
  libzhlgen/test/functions/win32/1.6.9/CrewMember.zhl
  libzhlgen/test/functions/win32/1.6.9/DroneSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/FTLButton.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipObject.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/SystemStoreBox.zhl
  libzhlgen/test/functions/win32/FTLGameStripped.h
  lua/modules/hyperspace.i
Labels: enhancement, translation, zhl

#569 mc visual bugfix
  CustomSystems.cpp
Labels: hs bug

#534 crew station UI fixes
  CustomCommandGui.cpp
Labels: vanilla bug

#577 Fix issue #561
  CustomEvents.cpp
Labels: vanilla bug

#570 Controllable artillery bugfixes
  ArtillerySystem.cpp
  CustomWeapons.cpp
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/ArtilleryBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ArtilleryBox.zhl
  libzhlgen/test/functions/win32/1.6.9/ArtilleryBox.zhl
Labels: hs bug

#541 Address issue #539
  CustomEvents.cpp
  CustomMap.cpp
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  StarMap.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/StarMap.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/StarMap.zhl
  libzhlgen/test/functions/win32/1.6.9/StarMap.zhl
Labels: vanilla bug

#588 No crash on invalid medical replacement
  CustomSystems.cpp
Labels: hs bug, vanilla bug

#578 Stop autofired charge guns from shooting more shots than they should
  CustomWeapons.cpp
Labels: hs bug

#579 Fix some edge cases with hacking removal
  CustomSystems.cpp
Labels: hs bug

#573 Fix bug with engineless player ships
  CMakeLists.txt
  CustomSystems.cpp
  FTL_HyperspaceGCC.cbp
  Mod Files/data/hyperspace.xml
Labels: vanilla bug

#568 fix how "all" works for systemList and systemPowerDependency
  StatBoost.cpp
Labels: hs bug

#536 Address issue #68
  CMakeLists.txt
  CustomCrew.cpp
  FTL_HyperspaceGCC.cbp
  Tasks.h
Labels: hs bug

#584 Wiki Tweaks
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#591 Updated Lua-Hyperspace-Module.md
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#542 Address issue #391
  CustomEvents.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
Labels: zhl, vanilla bug

#594 Fix artillery exclusivityGroup
  CustomSystems.cpp
Labels: hs bug

#595 Fix multi overcapacity duplicate bug
  CustomEquipment.cpp
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/EquipmentBoxItem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/EquipmentBoxItem.zhl
  libzhlgen/test/functions/win32/1.6.9/EquipmentBoxItem.zhl
Labels: hs bug
