Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2025-04, with the labels that each got.

#581 implement powerScalingShipTarget
  CrewMember_Extend.h
  Mod Files/data/hyperspace.xml
  StatBoost.cpp
  StatBoost.h
Labels: enhancement

#592 Oxygen features
  CustomCrew.cpp
  CustomSystems.cpp
  CustomSystems.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/OxygenSystem.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipGraph.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/OxygenSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipGraph.zhl
  libzhlgen/test/functions/win32/1.6.9/OxygenSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipGraph.zhl
  lua/InternalEvents.h
  lua/modules/hyperspace.i
  wiki/Lua-Defines-module.md
  wiki/Lua-Hyperspace-Module.md
Labels: hs bug, documentation, enhancement, zhl

#575 shieldWithoutSystem tag
  CustomOptions.h
  CustomSystems.cpp
  Mod Files/data/hyperspace.xml
  Resources.cpp
Labels: vanilla bug

#548 added TELEPORT_RECALL augment
  Augments.cpp
  CustomCrew.cpp
  CustomEvents.cpp
  CustomEvents.h
  Mod Files/data/blueprints.xml.append
  Mod Files/data/text_blueprints.xml.append
Labels: enhancement, translation

#587 Expose ShipRepairDrone members and fix inheritence
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/FTLGameStripped.h
  libzhlgen/test/functions/ELF_x86/FTLGameStripped.ELF32.h
  libzhlgen/test/functions/win32/FTLGameStripped.h
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement

#604 expose Room::FillSlot
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement

#601 Fixed a tpyo in hyperspace.i (MouseControl::selling)
  lua/modules/hyperspace.i
Labels: hs bug

#603 Fix for PR #591 for Lua-Hyperspace-Module.md
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#597 fix for when systemPowerScaling is omitted in a statBoost definition with systemPowerDependency.
  Mod Files/data/hyperspace.xml
  StatBoost.cpp
  StatBoost.h
Labels: hs bug

#605 Adding SHIP_STATUS render layer
  Misc.cpp
  lua/RenderEvents.h
  wiki/Lua-Defines-module.md
Labels: documentation, enhancement

#606 Add mouse scroll lua callback event
  Input.cpp
  lua/InternalEvents.h
  wiki/Lua-Defines-module.md
Labels: documentation, enhancement

#613 Fix array exposure
  lua/modules/hyperspace.i
Labels: hs bug

#590 More StarMap exposure
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement

#608 new CHOICE_BOX render layer
  Misc.cpp
  lua/RenderEvents.h
  wiki/Lua-Defines-module.md
Labels: documentation, enhancement

#582 customizable super shield drones
  CustomDrones.cpp
  CustomDrones.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/blueprints.xml.append
  Mod Files/data/text_misc.xml.append
  RedesignedTooltips.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/SuperShieldDrone.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SuperShieldDrone.zhl
  libzhlgen/test/functions/win32/1.6.9/SuperShieldDrone.zhl
Labels: enhancement, translation, zhl

#617 Fix multi over capacity item duplicate bug
  CustomEquipment.cpp
Labels: hs bug

#576 Add aug/cargo slot augment
  CustomEquipment.cpp
  CustomShipSelect.cpp
  Equipment_Extend.h
  Mod Files/data/blueprints.xml.append
  Mod Files/data/text_blueprints.xml.append
Labels: enhancement, translation

#598 Fix hazard icons to be properly displayed
  CMakeLists.txt
  Environments.h
  FTL_HyperspaceGCC.cbp
  Misc.cpp
Labels: vanilla bug

#619 Fix purchase limit being malfunctioning
  CustomStore.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/AugmentStoreBox.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponStoreBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/AugmentStoreBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponStoreBox.zhl
  libzhlgen/test/functions/win32/1.6.9/AugmentStoreBox.zhl
  libzhlgen/test/functions/win32/1.6.9/DroneStoreBox.zhl
Labels: hs bug, zhl

#626 Expose SpaceStatus::RenderWarningText and MouseControl::LoadTooltip
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement

#593 Customizable System UI
  CustomStore.cpp
  CustomSystems.cpp
  CustomSystems.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/example_system.lua
  Mod Files/data/hyperspace.xml
  Mod Files/data/text_misc.xml.append
  RenderReactorBar.cpp
  Resources.cpp
  SystemBox_Extend.cpp
  SystemBox_Extend.h
  System_Extend.cpp
  System_Extend.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/SystemControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SystemControl.zhl
  libzhlgen/test/functions/win32/1.6.9/SystemControl.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement, translation, zhl
