Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2025-05, with the labels that each got.

#635 Fix revisit with custom/temporal systems
  CustomSystems.cpp
Labels: hs bug

#636 disabled message shown when weapon is depowered
  CooldownNumbers.cpp
Labels: hs bug

#633 Wiki callbacks update
  wiki/Lua-Defines-module.md
Labels: documentation

#607 Updated BUILDING.DEVCONTAINER.md
  BUILDING.DEVCONTAINER.md
Labels: documentation

#612 Updated Lua-Hyperspace-Module.md
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#641 Fix edge case where GET_BEACON_HAZARD broke
  CustomEvents.cpp
  Misc.cpp
Labels: hs bug

#644 Halt non-hostile enemy's artillery firing
  ArtillerySystem.cpp
Labels: vanilla bug

#642 Reorganize static methods
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#647 Fix crew AI interactions with custom systems
  CustomSystems.cpp
Labels: hs bug
