Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2025-02, with the labels that each got.

#455 Expose ResourceEvent and Star map fields
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement

#363 Enemy Charge Box Position Fix
  CustomWeapons.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/Point.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/Ship.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponAnimation.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Point.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Ship.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponAnimation.zhl
  libzhlgen/test/functions/win32/1.6.9/Point.zhl
  libzhlgen/test/functions/win32/1.6.9/Ship.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponAnimation.zhl
Labels: enhancement, zhl

#418 Custom Tabbed Windows
  CMakeLists.txt
  CustomAugments.cpp
  CustomTabbedWindow.cpp
  CustomTabbedWindow.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  Mod Files/data/hyperspace.xml
  Mod Files/img/upgradeUI/Equipment/equipment_main_2.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/icon_crew.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/icon_equipment.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/icon_upgrades.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/left_off.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/left_on.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/left_select2.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/left_start_off.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/left_start_on.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/left_start_select2.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/right_end_off.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/right_end_on.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/right_end_select2.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/right_off.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/right_on.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/right_select2.png
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/CommandGui.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/CrewManifest.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/FocusWindow.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/TabbedWindow.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/Upgrades.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CommandGui.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CrewManifest.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/FocusWindow.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/TabbedWindow.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Upgrades.zhl
  libzhlgen/test/functions/win32/1.6.9/CommandGui.zhl
  libzhlgen/test/functions/win32/1.6.9/CrewManifest.zhl
  libzhlgen/test/functions/win32/1.6.9/FocusWindow.zhl
  libzhlgen/test/functions/win32/1.6.9/TabbedWindow.zhl
  libzhlgen/test/functions/win32/1.6.9/Upgrades.zhl
  lua/InternalEvents.h
  lua/RenderEvents.h
  lua/modules/hyperspace.i
  wiki/Lua-Defines-module.md
  wiki/Lua-Hyperspace-Module.md
Labels: hs bug, enhancement, zhl

#396 Add custom text style (in-text color)
  CMakeLists.txt
  CustomTextStyle.cpp
  CustomTextStyle.h
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/GL_Color.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/GL_Color.zhl
  libzhlgen/test/functions/win32/1.6.9/GL_Color.zhl
Labels: enhancement

#448 Exposing SoundControl::StopChannel
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/SoundControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SoundControl.zhl
  libzhlgen/test/functions/win32/1.6.9/SoundControl.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement, zhl

#406 Add scrolling tooltip and insert newline for multiple crew desc tooltip
  CustomCrew.cpp
  CustomOptions.h
  Input.cpp
  Mod Files/data/hyperspace.xml
  RedesignedTooltips.cpp
  RedesignedTooltips.h
  Resources.cpp
Labels: enhancement

#449 custom crew restart bugfix
  CustomShips.cpp
Labels: hs bug

#420 Apply custom choice colors to resources
  CustomColors.cpp
  CustomColors.h
  CustomOptions.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/ChoiceBox.zhl
  libzhlgen/test/functions/ELF_amd64/FTLGameStripped.h
  libzhlgen/test/functions/ELF_x86/1.6.13/ChoiceBox.zhl
  libzhlgen/test/functions/ELF_x86/FTLGameStripped.ELF32.h
  libzhlgen/test/functions/win32/1.6.9/ChoiceBox.zhl
  libzhlgen/test/functions/win32/FTLGameStripped.h
Labels: enhancement, zhl

#461 CustomTabbedWindow fix and options
  CustomTabbedWindow.cpp
  CustomTabbedWindow.h
  Resources.cpp
Labels: hs bug, enhancement

#456 Cloak render fix
  CustomOptions.h
  CustomShips.cpp
  FTLGameWin32.cpp
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/win32/1.6.9/CloakingSystem.zhl
Labels: vanilla bug

#462 exposure of all Description fields
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement

#463 fix a bug that a hovering info of an augment in the wrong page is shown
  CustomShipSelect.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/AugmentEquipBox.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/CrewEquipBox.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/EquipmentBox.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponEquipBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/AugmentEquipBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CrewEquipBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/EquipmentBox.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponEquipBox.zhl
  libzhlgen/test/functions/win32/1.6.9/AugmentEquipBox.zhl
  libzhlgen/test/functions/win32/1.6.9/CrewEquipBox.zhl
  libzhlgen/test/functions/win32/1.6.9/EquipmentBox.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponEquipBox.zhl
Labels: hs bug

#465 fix augSlots arrows
  CustomEquipment.cpp
  CustomShipSelect.cpp
Labels: enhancement

#444 added shotLimit tag
  CooldownNumbers.cpp
  CustomDamage.cpp
  CustomWeapons.cpp
  CustomWeapons.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Misc.cpp
  Mod Files/data/blueprints.xml.append
  Mod Files/data/text_misc.xml.append
  RedesignedTooltips.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/ProjectileFactory.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/TextString.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WarningMessage.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponControl.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ProjectileFactory.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/TextString.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WarningMessage.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/ProjectileFactory.zhl
  libzhlgen/test/functions/win32/1.6.9/TextString.zhl
  libzhlgen/test/functions/win32/1.6.9/WarningMessage.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponControl.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponSystem.zhl
  lua/InternalEvents.h
  wiki/Lua-Defines-module.md
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement, translation, zhl

#457 Added SECTOR_SCANNER augment
  Augments.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/blueprints.xml.append
  Mod Files/data/text_blueprints.xml.append
  libzhlgen/test/functions/ELF_amd64/1.6.13/StarMap.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/StarMap.zhl
  libzhlgen/test/functions/win32/1.6.9/StarMap.zhl
Labels: enhancement, translation, zhl

#432 Replacement implementation for Get_Drone_Subclass
  lua/modules/hyperspace.i
Labels: enhancement

#442 User can enable jump map wait menu (issue #439)
  CMakeLists.txt
  CustomMap.cpp
  CustomMap.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  libzhlgen/test/functions/ELF_amd64/1.6.13/GenericButton.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/MouseControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/GenericButton.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/MouseControl.zhl
  libzhlgen/test/functions/win32/1.6.9/GenericButton.zhl
  libzhlgen/test/functions/win32/1.6.9/MouseControl.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
  wiki/img/lua-hyperspace-module/map_fuel_text_nofuel.png
Labels: documentation, enhancement, zhl

#438 Drone UI Improvements (Issue #292)
  CMakeLists.txt
  CustomDrones.cpp
  CustomOptions.h
  Drones.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/DroneControl.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_amd64/FTLGameStripped.h
  libzhlgen/test/functions/ELF_x86/1.6.13/DroneControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/FTLGameStripped.ELF32.h
  libzhlgen/test/functions/win32/1.6.9/DroneControl.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
  libzhlgen/test/functions/win32/FTLGameStripped.h
Labels: enhancement, zhl

#431 Oxygen mechanics now function without system
  CMakeLists.txt
  CustomOptions.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  Mod Files/data/hyperspace.xml
  OxygenWithoutSystem.cpp
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/OxygenSystem.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/OxygenSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/win32/1.6.9/OxygenSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
Labels: enhancement, zhl

#473 Oxygen mechanics now function without system
  CMakeLists.txt
  CustomOptions.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  Mod Files/data/hyperspace.xml
  OxygenWithoutSystem.cpp
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/OxygenSystem.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/OxygenSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/win32/1.6.9/OxygenSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
Labels: enhancement, zhl

#477 add GET_BEACON_HAZARD callback event
  Misc.cpp
  lua/InternalEvents.h
  lua/LuaLibScript.h
  wiki/Lua-Defines-module.md
Labels: documentation, enhancement

#433 Custom Systems Implementation.
  .gitignore
  CMakeLists.txt
  CustomSystems.cpp
  CustomSystems.h
  CustomUpgrades.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  Global.cpp
  Misc.cpp
  Mod Files/data/example_system.lua
  Mod Files/data/hyperspace.xml
  Mod Files/img/wireUI/wire_custom.png
  Mod Files/img/wireUI/wire_custom_connector.png
  Mod Files/img/wireUI/wire_custom_connector_cap.png
  RenderReactorBar.cpp
  Resources.cpp
  SystemBox_Extend.cpp
  SystemBox_Extend.h
  Systems.h
  TemporalSystem.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/SystemBox.zhl
  libzhlgen/test/functions/ELF_amd64/FTLGameStripped.h
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SystemBox.zhl
  libzhlgen/test/functions/ELF_x86/FTLGameStripped.ELF32.h
  libzhlgen/test/functions/win32/1.6.9/ShipSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/SystemBox.zhl
  libzhlgen/test/functions/win32/FTLGameStripped.h
  lua/InternalEvents.h
  lua/LuaLibScript.h
  lua/RenderEvents.h
  lua/modules/hyperspace.i
  wiki/Lua-Defines-module.md
  wiki/Lua-Hyperspace-Module.md
Labels: enhancement, zhl

#471 Ship Switch
  CommandConsole.cpp
  CustomShips.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  libzhlgen/test/functions/ELF_amd64/1.6.13/CommandGui.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/PowerManager.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipGraph.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WorldManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CommandGui.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/PowerManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipGraph.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WorldManager.zhl
  libzhlgen/test/functions/win32/1.6.9/CommandGui.zhl
  libzhlgen/test/functions/win32/1.6.9/PowerManager.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipGraph.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
  libzhlgen/test/functions/win32/1.6.9/WorldManager.zhl
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement, zhl

#454 Controllable Artillery
  AdditionalWeaponSlots.cpp
  ArtilleryBarFix.cpp
  ArtillerySystem.cpp
  CustomOptions.h
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  Mod Files/data/blueprints.xml.append
  Mod Files/data/hyperspace.xml
  Mod Files/data/text_blueprints.xml.append
  Mod Files/img/misc/crosshairs_placed_fallback.png
  Mod Files/img/misc/crosshairs_placed_fallback_yellow.png
  Mod Files/img/mouse/mouse_crosshairs2_fallback.png
  Mod Files/img/mouse/mouse_crosshairs3_fallback.png
  Mod Files/img/systemUI/artilleryButton_off.png
  Mod Files/img/systemUI/artilleryButton_on.png
  Mod Files/img/systemUI/artilleryButton_select2.png
  Resources.cpp
  SystemBox_Extend.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/ArtillerySystem.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/WeaponControl.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ArtillerySystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/WeaponControl.zhl
  libzhlgen/test/functions/win32/1.6.9/ArtillerySystem.zhl
  libzhlgen/test/functions/win32/1.6.9/WeaponControl.zhl
Labels: enhancement, translation, zhl

#470 custom tutorials
  CMakeLists.txt
  CustomOptions.h
  CustomTutorial.cpp
  CustomTutorial.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  FTL_HyperspaceGCC.cbp
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/TutorialManager.zhl
  libzhlgen/test/functions/ELF_amd64/FTLGameStripped.h
  libzhlgen/test/functions/ELF_x86/1.6.13/TutorialManager.zhl
  libzhlgen/test/functions/ELF_x86/FTLGameStripped.ELF32.h
  libzhlgen/test/functions/win32/1.6.9/TutorialManager.zhl
  libzhlgen/test/functions/win32/FTLGameStripped.h
  lua/modules/hyperspace.i
  wiki/Lua-Hyperspace-Module.md
Labels: documentation, enhancement, zhl

#486 add WEAPON_COOLDOWN_MOD callback event
  Misc.cpp
  lua/InternalEvents.h
  wiki/Lua-Defines-module.md
Labels: enhancement

#481 Bomb bugfix
  CustomWeapons.cpp
Labels: hs bug

#475 Address issue #115
  CustomShips.cpp
Labels: hs bug

#467 Address issue #377
  CustomShipSelect.cpp
  CustomShipSelect.h
  CustomShips.cpp
Labels: hs bug

#489 fix event tooltip bug
  EventTooltip.cpp
Labels: hs bug

#469 Fix lockdown saving issue.
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Misc.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/AnimationTracker.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/Door.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/AnimationTracker.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Door.zhl
  libzhlgen/test/functions/win32/1.6.9/AnimationTracker.zhl
  libzhlgen/test/functions/win32/1.6.9/Door.zhl
Labels: zhl, vanilla bug

#464 Address issue #387
  CustomWeapons.cpp
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/CombatAI.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/Pointf.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CombatAI.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Pointf.zhl
  libzhlgen/test/functions/win32/1.6.9/CombatAI.zhl
  libzhlgen/test/functions/win32/1.6.9/Pointf.zhl
Labels: zhl, vanilla bug

#492 added the HULL command to the hyperspace.xml's console command list
  Mod Files/data/hyperspace.xml
Labels: documentation

#468 Random Ship Bugfix
  CustomScoreKeeper.cpp
  CustomShipSelect.cpp
  FTLGameELF32.h
  FTLGameELF64.h
  FTLGameWin32.h
  libzhlgen/test/functions/ELF_amd64/1.6.13/ScoreKeeper.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ScoreKeeper.zhl
  libzhlgen/test/functions/win32/1.6.9/ScoreKeeper.zhl
Labels: hs bug

#512 Fix issue #508
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Misc.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/SpaceStatus.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/SpaceStatus.zhl
  libzhlgen/test/functions/win32/1.6.9/SpaceStatus.zhl
Labels: vanilla bug

#507 shotLimit fix
  CustomWeapons.cpp
Labels: hs bug

#509 Properly expose CustomDamage and related classes
  CustomDamage.h
  lua/modules/hyperspace.i
Labels: hs bug

#496 Custom Tabs dynamic rendering for selected tabs button
  CustomTabbedWindow.cpp
  Mod Files/data/hyperspace.xml
  Mod Files/img/upgradeUI/Equipment/tabButtons/select_button.png
  Mod Files/img/upgradeUI/Equipment/tabButtons/select_button_end.png
Labels: enhancement
