Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2025-01, with the labels that each got.

#392 Custom Clonebay
  CustomCrew.cpp
  CustomSystems.cpp
  CustomSystems.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  libzhlgen/test/functions/ELF_amd64/1.6.13/CloneSystem.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/CloneSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipManager.zhl
  libzhlgen/test/functions/win32/1.6.9/CloneSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipManager.zhl
  lua/InternalEvents.h
  wiki/Lua-Defines-module.md
Labels: enhancement, zhl

#412 Fix showReactor bug
  CustomShipSelect.cpp
Labels: hs bug

#434 Vector template docs
  wiki/Lua-Hyperspace-Module.md
Labels: documentation

#435 SHIP ALL now works for vanilla ships as well
  CommandConsole.cpp
  Mod Files/data/hyperspace.xml
  Mod Files/data/text-ru.xml.append
Labels: hs bug

#421 Improved lua errors
  CMakeLists.txt
  FTL_HyperspaceGCC.cbp
  Misc.cpp
  lua/EventEnums.h
  lua/InternalEvents.h
  lua/RenderEvents.h
  lua/modules/defines.i
Labels: enhancement

#424 Fix ELF segment size calculation
  SigScan.cpp
Labels: enhancement

#415 Adding current event debt to calculation of the cost requirements of following event
  CustomEvents.cpp
Labels: vanilla bug

#429 Fix Hacking self-ionizing exploit
  Balance.cpp
  Balance.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  Resources.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/ShipSystem.zhl
  libzhlgen/test/functions/win32/1.6.9/ShipSystem.zhl
Labels: zhl, vanilla bug
