Repository FTL-Hyperspace/FTL-Hyperspace, pull requests merged in 2025-07, with the labels that each got.

#674 Russian translation update
  Mod Files/data/text-ru.xml.append
Labels: translation

#665 bounds checking and exception macro tweaks
  lua/modules/hyperspace.i
Labels: hs bug

#679 Implement boss level behavior override for custom sectors
  CustomEvents.cpp
  CustomEvents.h
  FTLGameELF32.cpp
  FTLGameELF32.h
  FTLGameELF64.cpp
  FTLGameELF64.h
  FTLGameWin32.cpp
  FTLGameWin32.h
  Mod Files/data/hyperspace.xml
  StarMap.cpp
  libzhlgen/test/functions/ELF_amd64/1.6.13/BlueprintManager.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/EventGenerator.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/Point.zhl
  libzhlgen/test/functions/ELF_amd64/1.6.13/StarMap.zhl
  libzhlgen/test/functions/ELF_amd64/FTLGameStripped.h
  libzhlgen/test/functions/ELF_x86/1.6.13/BlueprintManager.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/EventGenerator.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/Point.zhl
  libzhlgen/test/functions/ELF_x86/1.6.13/StarMap.zhl
  libzhlgen/test/functions/ELF_x86/FTLGameStripped.ELF32.h
  libzhlgen/test/functions/win32/1.6.9/BlueprintManager.zhl
  libzhlgen/test/functions/win32/1.6.9/EventGenerator.zhl
  libzhlgen/test/functions/win32/1.6.9/Point.zhl
  libzhlgen/test/functions/win32/1.6.9/StarMap.zhl
  libzhlgen/test/functions/win32/FTLGameStripped.h
Labels: enhancement, zhl
